---

- name: installing nginx and start the server
  hosts: servers
  become: yes
  tasks: 
    - name: installing nginx
      apt:
        name: nginx
        state: latest
    
    - name: start nginx
      service: 
        name: nginx
        state: started
        enabled: yes

    - name: serving html page
      copy:
        src: /home/ubuntu/index.html
        dest: /var/www/html/
          


